# Generated by Django 5.2.3 on 2025-07-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
